### ISSUE TITLE
京东财富岛经常这样报错

### ISSUE THREAD

**Issue by 471309682** [KingRan/KR#109]
<img width="972" alt="WeChat20d500b12b905960bf7f0afd8209234d" src="https://user-images.githubusercontent.com/22569284/166684960-9cd20521-a17b-498b-8ecc-8abcda62ee3d.png">

**Comment by 471309682** [comment]
"Response code 401 (Unauthorized)"
京喜财富岛 QueryUserInfo API请求失败，请检查网路重试

❗️京喜财富岛, 错误!
TypeError: Cannot read properties of undefined (reading 'LeadInfo')
    at cfd (/ql/data/scripts/KingRan_KR/jd_cfd.js:131:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/KingRan_KR/jd_cfd.js:94:7

**Comment by lxmicode** [comment]
遇到一样的问题，其他作者正常，可以同步更新下

**Comment by KingRan** [comment]
更新试试

**Comment by lxmicode** [comment]
还是会

**Comment by lxmicode** [comment]
应该是服务器IP问题，有一些就正常

**Comment by KingRan** [comment]
应该是ip的问题  已经和其他库的一样了
