### ISSUE TITLE
禁用重复任务无法获取token

### ISSUE THREAD

**Issue by dycwuxing** [KingRan/KR#217]
已经按照提示增加了变量,仍旧无法获取token

<img width="539" alt="image" src="https://user-images.githubusercontent.com/44988562/187056319-61220a29-4a91-4c6d-9b5a-694f22cbe176.png">

======================
===> 禁用重复任务开始 <===
加载推送功能中...
❌无法获取 token!!!
Traceback (most recent call last):
  File "jd_disable.py", line 172, in get_token
    if getversion() == 1:
  File "jd_disable.py", line 89, in getversion
    data = json.loads(response.content.decode("utf-8"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

💔禁用重复任务失败

无法获取 token!!!

**Comment by Peter-90** [comment]
我的是报这个错：
===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
KingRan_KR
❌无法获取 tasklist!!!

**Comment by 501658362** [comment]
## 开始执行... 2022-09-08 14:49:50

===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
KingRan_KR
Traceback (most recent call last):
  File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 192, in <module>
    filter_list, res_list = filter_res_sub(tasklist)
  File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 70, in filter_res_sub
    if task.get("command").find(sub) == -1:
AttributeError: 'str' object has no attribute 'get'

## 执行结束... 2022-09-08 14:49:51 耗时 1 秒

**Comment by 1003975584** [comment]
> ## 开始执行... 2022-09-08 14:49:50
> ===> 禁用重复任务开始 <=== 加载推送功能中...
> 
> === 你选择过滤的任务前缀为 === KingRan_KR Traceback (most recent call last): File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 192, in filter_list, res_list = filter_res_sub(tasklist) File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 70, in filter_res_sub if task.get("command").find(sub) == -1: AttributeError: 'str' object has no attribute 'get'
> 
> ## 执行结束... 2022-09-08 14:49:51 耗时 1 秒

61行tasklist = datas.get("data") 改为tasklist = datas.get("data").get(data)

**Comment by esacmsn** [comment]
> 

我的也已一样
