### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by FulLiunian** [KingRan/KR#221]
## 开始执行... 2022-09-04 13:21:04

🔔京东CK检测, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/9/4 13:21:04=====================

node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module './ql'
Require stack:
- /ql/data/scripts/KingRan_KR/jd_CheckCK.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/KingRan_KR/jd_CheckCK.js:16:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/KingRan_KR/jd_CheckCK.js' ]
}

Node.js v18.3.0

## 执行结束... 2022-09-04 13:21:05 耗时 1 秒

Error: Cannot find module './function/zjdtool.js'
Require stack:
- /ql/data/scripts/KingRan_KR/jd_zjd.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/root/.local/share/pnpm/global/5/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/KingRan_KR/jd_zjd.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/root/.local/share/pnpm/global/5/.pnpm/ts-node@10.8.1_hwzkig5zd3nmhninrbdilxyfci/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/root/.local/share/pnpm/global/5/.pnpm/ts-node@10.8.1_hwzkig5zd3nmhninrbdilxyfci/node_modules/ts-node/src/index.ts:1600:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/KingRan_KR/jd_zjd.ts' ]
}

大佬能告知下这是什么情况吗？我运行大部分脚本都这样报错！在TG 以及GitHub上没看到详细的相关文档

**Comment by woji95** [comment]
重装青龙吧，脚本路径不对

**Comment by FulLiunian** [comment]
我这边是按照GitHub上面的青龙脚本进行安装的，我运行别的脚本也没有这个问题呀？
我更新到最新的青龙2.14.4 还是报错
node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module './USER_AGENTS'
Require stack:
- /ql/data/scripts/KingRan_KR/jd_jx_sign.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /ql/data/scripts/KingRan_KR/jd_jx_sign.js:21:50292
    at new Promise (<anonymous>)
    at TotalBean (/ql/data/scripts/KingRan_KR/jd_jx_sign.js:21:49914)
    at /ql/data/scripts/KingRan_KR/jd_jx_sign.js:21:43523
    at Object.<anonymous> (/ql/data/scripts/KingRan_KR/jd_jx_sign.js:21:44053)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/KingRan_KR/jd_jx_sign.js' ]
}

Node.js v18.3.0

**Comment by FulLiunian** [comment]
JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

**Comment by FulLiunian** [comment]
导入进去大部分都有报错，头疼

**Comment by FulLiunian** [comment]
青龙2.10.X以上版本默认的路径都是/ql/scripts/KingRan_KR 不是/ql/data/scripts/KingRan_KR/
