### ISSUE TITLE
大佬,京东特价版赚金币更新出错了

### ISSUE THREAD

**Issue by Sxxiong** [KingRan/KR#276]

**Comment by Sxxiong** [comment]
![d5d2692e3d98f8ef22186309180a372](https://user-images.githubusercontent.com/26076326/205238714-3f457c8c-5fd7-43bf-a9fb-d823a175a15f.png)
**code is not define**

**Comment by xiaobei206** [comment]
ReferenceError: code is not defined
    at invite2 (/ql/data/scripts/KingRan_KR/jd_speed_sign.js:812:131)
    at jdGlobal (/ql/data/scripts/KingRan_KR/jd_speed_sign.js:100:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/KingRan_KR/jd_speed_sign.js:76:7

**Comment by xiuzhufgh** [comment]
ReferenceError: code is not defined
    at invite2 (/ql/data/scripts/KingRan_KR/jd_speed_sign.js:812:131)
    at jdGlobal (/ql/data/scripts/KingRan_KR/jd_speed_sign.js: 100:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/data/scripts/KingRan_KR/jd_speed_sign.js:76:7
