### ISSUE TITLE
任务出错代码咨询（不是个别任务，普遍报这个错）

### ISSUE THREAD

**Issue by yuhouyanran** [KingRan/KR#293]
## 开始执行... 2023-01-08 17:16:04

🔔读秒拼手速通用活动, 开始!

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：1/8/2023, 17:16:06=====================

KingRan 频道通知：https://t.me/KingRan521

云服务器IP须知：域名前缀为 'lzdz' 的禁用勿跑容易黑号

/usr/local/bin/ds:2
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/KingRan_KR/function/cache/index.js:1:9455)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Node.js v18.12.1

**Comment by yuhouyanran** [comment]
还有一种报错是命令未添加“now”，随机延迟xx秒之后再次运行。

**Comment by arieszengsky** [comment]
我也是报这个错，还不知道怎么处理。群晖的docker
# 开始执行... 2023-03-08 12:24:20


🔔东东农场快速浇水, 开始!
/usr/local/bin/ds:2
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/KingRan_KR/function/cache/index.js:1:9455)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Node.js v18.12.1


## 执行结束... 2023-03-08 12:24:21  耗时 1 秒

**Comment by yuhouyanran** [comment]
> 我也是报这个错，还不知道怎么处理。群晖的docker
> 
> # 开始执行... 2023-03-08 12:24:20
> 🔔东东农场快速浇水, 开始! /usr/local/bin/ds:2
> 
> # -_- coding: utf-8 -_-
> ^
> 
> SyntaxError: Invalid or unexpected token at Object.compileFunction (node:vm:360:18) at wrapSafe (node:internal/modules/cjs/loader:1088:15) at Module._compile (node:internal/modules/cjs/loader:1123:27) at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) at Module.load (node:internal/modules/cjs/loader:1037:32) at Module._load (node:internal/modules/cjs/loader:878:12) at Module.require (node:internal/modules/cjs/loader:1061:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (/ql/data/scripts/KingRan_KR/function/cache/index.js:1:9455) at Module._compile (node:internal/modules/cjs/loader:1159:14)
> 
> Node.js v18.12.1
> 
> ## 执行结束... 2023-03-08 12:24:21 耗时 1 秒

用这个库了，挺好用的：【Faker2】有助力池 290+
拉库命令：
ql repo https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator" "main"
