### ISSUE TITLE
领京豆报错TypeError: Cannot read properties of undefined (reading 'doneTask')求解

### ISSUE THREAD

**Issue by shuffleer** [KingRan/KR#299]
领京豆报错求解，就不领主页那个累计天数增加豆子奖励的签到
TypeError: Cannot read properties of undefined (reading 'doneTask')
    at /ql/data/scripts/KingRan_KR/jd_ljd.js:126:71
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/KingRan_KR/jd_ljd.js:308:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[从京东首页领京豆进入] 正在做任务...
活动太火爆啦~
活动太火爆啦~
TypeError: Cannot read properties of undefined (reading 'awardResultFlag')
    at /ql/data/scripts/KingRan_KR/jd_ljd.js:116:46
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/KingRan_KR/jd_ljd.js:308:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'taskInfos')
    at /ql/data/scripts/KingRan_KR/jd_ljd.js:125:59
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/KingRan_KR/jd_ljd.js:308:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[从京东首页领京豆进入] 正在做任务...
活动太火爆啦~
活动太火爆啦~
正在发送通知...

**Comment by SeanLite2023** [comment]
借楼同问
我的 -- 签到领豆 
貌似不行
请大佬确认，感谢

**Comment by shuffleer** [comment]
> 



> 借楼同问 我的 -- 签到领豆 貌似不行 请大佬确认，感谢

我把其他库的提一个脚本出来用了

**Comment by google-mirror** [comment]
> > 
> 
> > 借楼同问 我的 -- 签到领豆 貌似不行 请大佬确认，感谢
> 
> 我把其他库的提一个脚本出来用了

那个

**Comment by shuffleer** [comment]
> > > 
> > 
> > 
> > > 借楼同问 我的 -- 签到领豆 貌似不行 请大佬确认，感谢
> > 
> > 
> > 我把其他库的提一个脚本出来用了
> 
> 那个

链接：https://pan.baidu.com/s/1tTuSueAdVu6iDPqgiBPKgw?pwd=1024 
提取码：1024

**Comment by google-mirror** [comment]
> > > > 
> > > 
> > > 
> > > > 借楼同问 我的 -- 签到领豆 貌似不行 请大佬确认，感谢
> > > 
> > > 
> > > 我把其他库的提一个脚本出来用了
> > 
> > 
> > 那个
> 
> 链接：https://pan.baidu.com/s/1tTuSueAdVu6iDPqgiBPKgw?pwd=1024 提取码：1024

666, 大佬还有其他分享吗
