### ISSUE TITLE
报错jd_redrain.js

### ISSUE THREAD

**Issue by happy-func** [KingRan/KR#31]
```js
TypeError: Cannot read properties of undefined (reading '3')
    at /ql/scripts/KingRan_KR/jd_redrain.js:177:61
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/KingRan_KR/jd_redrain.js:297:5721)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
看代码虽然解析错误了，但是请求应该是成功了。但是看手机上j豆这个时间点并没有获取到。
加一句，半点jd雨成功了，手机上也能看到这个时间点获取到了.

**Comment by happy-func** [comment]
又看了下新的日志，发现半点也是这样了。应该是跟活动是否有效有关吧，不给作者找活了。
