### ISSUE TITLE
运行的时候提示找不到模块tough-cookie

### ISSUE THREAD

**Issue by 554320838** [KingRan/KR#37]
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/KingRan_KR/jd_fcwb_help.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.initGotEnv (/ql/scripts/KingRan_KR/jd_fcwb_help.js:313:3796)
    at Object.get (/ql/scripts/KingRan_KR/jd_fcwb_help.js:313:4567)
    at /ql/scripts/KingRan_KR/jd_fcwb_help.js:249:11
    at new Promise (<anonymous>)
    at takeRequest (/ql/scripts/KingRan_KR/jd_fcwb_help.js:248:12)
    at main (/ql/scripts/KingRan_KR/jd_fcwb_help.js:150:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/KingRan_KR/jd_fcwb_help.js' ]
}

Node.js v17.5.0

**Comment by bertms** [comment]
进入容器运行  pnpm install tough-cookie -g
