### ISSUE TITLE
京东保价运行出错

### ISSUE THREAD

**Issue by cmazfuture** [KingRan/KR#38]
日志-京东保价
## 开始执行... 2022-03-06 19:59:33

🔔京东保价, 开始!

====================共12个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/3/6 19:59:34=====================

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'jsdom'
Require stack:
- /ql/scripts/KingRan_KR/jd_price.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/KingRan_KR/jd_price.js:25:28)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/KingRan_KR/jd_price.js' ]
}

## 执行结束... 2022-03-06 19:59:34 耗时 1 秒

**Comment by cmazfuture** [comment]
解决了。依赖少了
