### ISSUE TITLE
盲盒错误

### ISSUE THREAD

**Issue by dark748001** [KingRan/KR#49]
*****开始【京东账号1】番茄恶魔*********

新的盲盒任务已经准备好: https://anmp.jd.com/babelDiy/Zeus/3qCGZmu8p9zXYQuixw8B2TtDwkJm/index.html，准备开始薅豆

盲盒任务url:https://anmp.jd.com/babelDiy/Zeus/3qCGZmu8p9zXYQuixw8B2TtDwkJm/index.html

❗️盲盒任务抽京豆, 错误!
TypeError: Cannot read properties of undefined (reading 'bless')
    at /ql/scripts/KingRan_KR_main_jd_mhtask.js:134:43
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/KingRan_KR_main_jd_mhtask.js:289:4791)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by dark748001** [comment]
安装了依赖也是想错.js py的依赖都安装好了的

**Comment by KingRan** [comment]
活动问题
