### ISSUE TITLE
入会开卡领取礼提示错误，大佬指点一下

### ISSUE THREAD

**Issue by fenghao012** [KingRan/KR#56]
TypeError: Cannot read properties of undefined (reading 'split')
    at run (/ql/scripts/KingRan_KR/jd_OpenCard_Force.js:75:56)
    at /ql/scripts/KingRan_KR/jd_OpenCard_Force.js:62:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by KingRan** [comment]
> TypeError: Cannot read properties of undefined (reading 'split')
>     at run (/ql/scripts/KingRan_KR/jd_OpenCard_Force.js:75:56)
>     at /ql/scripts/KingRan_KR/jd_OpenCard_Force.js:62:13
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

更新试试
